name: Deploy to Docker Hub

on:
  push:
    branches: ["main"] # Executa o deploy sempre que houver push na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/favorites/docker/setup-buildx-action@v3 # Prepara o ambiente Docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: feliperaac/git-commit-mirror:latest # Sua imagem com o usuário correto do Docker Hub
